Console.WriteLine(GrasshoperSummation.Summation(1));
Console.WriteLine(GrasshoperSummation.Summation(8));
Console.WriteLine(GrasshoperSummation.Summation(22));
Console.WriteLine(GrasshoperSummation.Summation(100));
Console.WriteLine(GrasshoperSummation.Summation(213));
Console.WriteLine("---------gauss trick---------");
Console.WriteLine(GrasshoperSummation.GaussTrick(1));
Console.WriteLine(GrasshoperSummation.GaussTrick(8));
Console.WriteLine(GrasshoperSummation.GaussTrick(22));
Console.WriteLine(GrasshoperSummation.GaussTrick(100));
Console.WriteLine(GrasshoperSummation.GaussTrick(213));