Console.WriteLine(StringEndsWith.StrEndsWith("samurai", "ai"));
Console.WriteLine(StringEndsWith.StrEndsWith("sumo", "omo"));
Console.WriteLine(StringEndsWith.StrEndsWith("ninja", "ja"));
Console.WriteLine(StringEndsWith.StrEndsWith("sensei", "i"));
Console.WriteLine(StringEndsWith.StrEndsWith("samurai", "ra"));
Console.WriteLine(StringEndsWith.StrEndsWith("abc", "abcd"));
Console.WriteLine(StringEndsWith.StrEndsWith("abc", "abc"));
Console.WriteLine(StringEndsWith.StrEndsWith("abcabc", "bc"));
Console.WriteLine(StringEndsWith.StrEndsWith("ails", "fails"));
Console.WriteLine(StringEndsWith.StrEndsWith("fails", "ails"));
Console.WriteLine(StringEndsWith.StrEndsWith("this", "fails"));
Console.WriteLine(StringEndsWith.StrEndsWith("abc", ""));
Console.WriteLine(StringEndsWith.StrEndsWith(":-)", ":-("));
Console.WriteLine(StringEndsWith.StrEndsWith("!@#$%^&*() :-)", ":-)"));
Console.WriteLine(StringEndsWith.StrEndsWith("abc\n", "abc"));